### ISSUE TITLE
Travis caching

### ISSUE THREAD

**Issue by mspraggs** [aportelli/LatAnalyze3#7]
In case you haven't already found it, the docs on caching in Travis CI are here: https://docs.travis-ci.com/user/caching/

**Comment by aportelli** [comment]
Hi Matt, thanks for suggesting Travis and for the link, it has been really useful. It took me 29 builds to make the bloody thing works, mainly because some GNU tools have some undocumented, non-retrocompatible changes between versions and Travis Linux VM uses a rather old version of Ubuntu.
Now everything is working and I would like to believe that this painful exercise has improved the portability significantly. Through Travis I am checking that LatAnalyze is building correctly for linux/OS X with clang and GCC.
